// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vokabeltrainer.Core.VokabelContext;

#nullable disable

namespace Vokabeltrainer.Core.Migrations
{
    [DbContext(typeof(VokabelDataContext))]
    [Migration("20241005092440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Vokabeltrainer.Core.Models.Vokabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Deutsch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Englisch")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zaehler")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vokabeln");
                });
#pragma warning restore 612, 618
        }
    }
}
