// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vokabeltrainer.Core.VokabelContext;

#nullable disable

namespace Vokabeltrainer.Core.Migrations
{
    [DbContext(typeof(VokabelDataContext))]
    [Migration("20260909224000_FreigabedatumFuerVokabeln")]
    partial class FreigabedatumFuerVokabeln
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Vokabeltrainer.Core.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Cdt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Falsche")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Mdt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Richtige")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StopTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Zeit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Vokabeltrainer.Core.Models.Vokabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Cdt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deutsch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Englisch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Freigabedatum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Mdt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zaehler")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vokabeln");
                });
#pragma warning restore 612, 618
        }
    }
}
